#!/usr/bin/perl

# Wyświetla ekspertów z bazy SQLite

use strict;
use warnings;
use CGI;
use DBI;

my $dbfile = "../main.db";
my $dsn      = "dbi:SQLite:dbname=$dbfile";
my $dbh = DBI->connect($dsn, "", "", {
   PrintError       => 0,
   RaiseError       => 1,
   AutoCommit       => 1,
   FetchHashKeyName => 'NAME_lc',
});

my $cgi = CGI->new;

print $cgi->header(
-type => "text/html",
-charset => "utf-8",
);

print "<html><head><title>Ekspertyzanci</title></head>";
print "<body>";
print "<h1>Lista ekspertów</h1>";
print "<p>Kliknij na eksperta, aby dowiedzieć się więcej.</p>";

my $sth = $dbh->prepare("SELECT login,name,surname FROM experts");
$sth->execute();
while (my $row = $sth->fetchrow_hashref) 
{
	print "<p><a href='details?$row->{login}'>$row->{name} $row->{surname}</a></p>";
}

print "</body></html>";
