#!/usr/bin/perl

# Wyświetla listę pytań

use strict;
use warnings;
use CGI;
use DBI;

my $dbfile = "../main.db";
my $dsn      = "dbi:SQLite:dbname=$dbfile";
my $dbh = DBI->connect($dsn, "", "", {
   PrintError       => 0,
   RaiseError       => 1,
   AutoCommit       => 1,
   FetchHashKeyName => 'NAME_lc',
});

my $cgi = CGI->new;

print $cgi->header(
-type => "text/html",
-charset => "utf-8",
);

print "<html><head><title>Ekspertyzanci</title></head>";
print "<body>";
print "<h1>Lista pytań</h1>";
print "<p>Wybierz pytanie</p>";

my $sth = $dbh->prepare("SELECT questions.text,questions.id,users.login FROM questions JOIN users ON users.login = questions.userlogin");
$sth->execute();
while (my $row = $sth->fetchrow_hashref) 
{
	print "<p><a href='question?$row->{id}'>$row->{text}</a> zadane przez $row->{login}</p>";
}

print "</body></html>";
